version: '3'
services:
  app:
    image: node:16
    container_name: node
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'npm install -g npm@latest && npm install && npm run start'
    ports:
      - "5173:5173"
    networks:
      portfolio_network:

networks:
  portfolio_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16