version: '3'
services:
  app:
    image: node:16
    container_name: node
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'npm install -g npm@latest && npm install && npm run start --force'
    ports:
      - "5173:5173"
      - "4173:4173"
    networks:
      segundo_portfolio_network:

networks:
  segundo_portfolio_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
